import Head from 'next/head'
import Link from "next/link";
import {users} from "@/data";


export async function getStaticProps() {
    return {
        props: {
            users,
        },
    };
}

export default function Blog({users}) {
    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <h1>Blog page</h1>
                {users.map((user => {
                    return <div>
                        <Link href={`/blog/${user.id}`}>{user.id}</Link>
                        <p>{user.first_name}</p>
                        <p>{user.last_name}</p>
                        <p>{user.email}</p>
                        <p>{user.gender}</p>
                        <p>{user.ip_address}</p>
                    </div>
                }))}
            </main>
        </>
    )
}
